### ISSUE TITLE
[Fixed, Testing]TG robot setup failed.

### ISSUE THREAD

**Issue by jiayihello** [lotusproxy/lotusboard-docker#2]
来自TG的错误：Bad Request: bad webhook: An HTTPS URL must be provided for webhook

**Comment by lotusproxy** [comment]
Will take a look on that

**Comment by lotusproxy** [comment]
> 来自TG的错误：Bad Request: bad webhook: An HTTPS URL must be provided for webhook

Fixed, please switch to main/neo-main branch and do `git submodule update --remote` to update

**Comment by lotusproxy** [comment]
Please tell me whether it's fixed or not, if it's working i'll merge it into stable version

**Comment by jiayihello** [comment]
> Please tell me whether it's fixed or not, if it's working i'll merge it into stable version

Still not working

**Comment by jiayihello** [comment]
![image](https://github.com/lotusproxy/lotusboard-docker/assets/103972455/61547095-2ccf-4c29-8bae-db148c91a0f0)

**Comment by lotusproxy** [comment]
> ![image](https://user-images.githubusercontent.com/103972455/255066346-61547095-2ccf-4c29-8bae-db148c91a0f0.png)

Have you set SiteURL(站点设定)?

**Comment by jiayihello** [comment]
> > ![图像](https://user-images.githubusercontent.com/103972455/255066346-61547095-2ccf-4c29-8bae-db148c91a0f0.png)
> 
> 您是否设置了SiteURL（站点设置）？

Yes, I set it up.

**Comment by lotusproxy** [comment]
show me your .gitsubmodule

**Comment by jiayihello** [comment]
> .gitsubmodule

[submodule "lotusboard"]
        path = lotusboard
        url = https://github.com/lotusproxy/lotusboard.git
        branch = neo-latest-stable

**Comment by lotusproxy** [comment]
branch = neo-main

then git submodule update --remote

and then everything should be fine

**Comment by jiayihello** [comment]
> branch = neo-main
> 
> then git submodule update --remote
> 
> and then everything should be fine

Okay, thank you
